# coolify.yaml
# Coolify deployment configuration for Mevzuat MCP Server

services:
  mevzuat-api:
    image: "mevzuat-mcp:latest"
    build:
      context: "."
      dockerfile: "Dockerfile"
    
    # Environment variables for the application
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
      
    # Port mapping
    ports:
      - "8000:8000"
    
    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Restart policy
    restart: unless-stopped
    
    # Resource constraints
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
    
    # Volume mounts for logs persistence
    volumes:
      - logs_data:/app/logs
    
    # Labels for Coolify management
    labels:
      - "coolify.managed=true"
      - "coolify.name=mevzuat-api"
      - "coolify.type=application"

# Named volumes
volumes:
  logs_data:
    driver: local

# Network configuration
networks:
  default:
    name: mevzuat-network
