# docker-compose.yml
# Coolify deployment configuration for Mevzuat MCP Server
# Domain: mcp-mevzuat.dosya.ai

version: '3.8'

services:
  mevzuat-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'mevzuat-mcp:latest'
    
    # Port configuration - Coolify handles external routing
    expose:
      - "8000"
    
    # Environment variables - set these in Coolify dashboard
    environment:
      # Core settings
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=production
      - WORKERS=2
      
      # Security
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      
      # CORS - Flowise integration
      - ALLOWED_ORIGINS=https://flowise.software.vision,https://mcp-mevzuat.dosya.ai
      
      # API settings
      - API_TIMEOUT=30.0
      - LOG_LEVEL=INFO
      - RATE_LIMIT_PER_MINUTE=120
      
      # Coolify specific
      - COOLIFY_BRANCH=main
      - COOLIFY_RESOURCE_UUID=${COOLIFY_RESOURCE_UUID}
      - COOLIFY_CONTAINER_NAME=${COOLIFY_CONTAINER_NAME}
      - SERVICE_URL_MEVZUAT-API=https://mcp-mevzuat.dosya.ai
      - SERVICE_FQDN_MEVZUAT-API=mcp-mevzuat.dosya.ai
      - COOLIFY_URL=https://mcp-mevzuat.dosya.ai
      - COOLIFY_FQDN=mcp-mevzuat.dosya.ai
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Volume mounts for logs persistence
    volumes:
      - mevzuat_logs:/app/logs
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Labels for Coolify management
    labels:
      - "coolify.managed=true"
      - "coolify.name=mevzuat-api"
      - "coolify.type=application"
      - "traefik.enable=true"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-0-${COOLIFY_RESOURCE_UUID}-mevzuat-api.entryPoints=http"
      - "traefik.http.routers.http-0-${COOLIFY_RESOURCE_UUID}-mevzuat-api.middlewares=redirect-to-https"
      - "traefik.http.routers.http-0-${COOLIFY_RESOURCE_UUID}-mevzuat-api.rule=Host(`mcp-mevzuat.dosya.ai`) && PathPrefix(`/`)"
      - "traefik.http.routers.https-0-${COOLIFY_RESOURCE_UUID}-mevzuat-api.entryPoints=https"
      - "traefik.http.routers.https-0-${COOLIFY_RESOURCE_UUID}-mevzuat-api.middlewares=gzip"
      - "traefik.http.routers.https-0-${COOLIFY_RESOURCE_UUID}-mevzuat-api.rule=Host(`mcp-mevzuat.dosya.ai`) && PathPrefix(`/`)"
      - "traefik.http.routers.https-0-${COOLIFY_RESOURCE_UUID}-mevzuat-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.https-0-${COOLIFY_RESOURCE_UUID}-mevzuat-api.tls=true"

# Named volumes
volumes:
  mevzuat_logs:
    driver: local

# Networks
networks:
  default:
    name: coolify-network
