# docker-compose.yml
# Coolify deployment configuration for Mevzuat MCP Server
# Domain: mcp-mevzuat.dosya.ai

version: '3.8'

services:
  mevzuat-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'mevzuat-mcp:latest'
    
    # Port configuration - Coolify handles external routing
    expose:
      - "8000"
    
    # Environment variables - minimal configuration
    environment:
      # Core settings
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=production
      - WORKERS=2
      
      # Security - set this in Coolify environment variables
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      
      # CORS - Flowise integration
      - ALLOWED_ORIGINS=https://flowise.software.vision,https://mcp-mevzuat.dosya.ai
      
      # API settings
      - API_TIMEOUT=30.0
      - LOG_LEVEL=INFO
      - RATE_LIMIT_PER_MINUTE=120
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Volume mounts for logs persistence
    volumes:
      - mevzuat_logs:/app/logs
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Labels - Coolify will auto-generate these
    labels:
      - "coolify.managed=true"

# Named volumes
volumes:
  mevzuat_logs:
    driver: local

# Networks - Coolify will auto-generate these
networks:
  default:
